export enum AuditEntityType {
    INCOME = 'INCOME',
    EXPENSE = 'EXPENSE',
    MONTHLY_CLOSING = 'MONTHLY_CLOSING',
    VENDOR = 'VENDOR',
    BILLING_CATEGORY = 'BILLING_CATEGORY',
    REVENUE_AGREEMENT = 'REVENUE_AGREEMENT',
    PARTICIPANT_SETTLEMENT = 'PARTICIPANT_SETTLEMENT',
    PARTICIPANT_PAYOUT = 'PARTICIPANT_PAYOUT',
}